package com.olivee.hrmanager.web.entity;

// Generated 2012-9-28 17:46:35 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * HrAwardWinning generated by hbm2java
 */
public class HrAwardWinning implements java.io.Serializable {

	private String id;
	private String employeeid;
	private String name;
	private String level;
	private Date getdate;

	public HrAwardWinning() {
	}

	public HrAwardWinning(String id, String employeeid) {
		this.id = id;
		this.employeeid = employeeid;
	}

	public HrAwardWinning(String id, String employeeid, String name,
			String level, Date getdate) {
		this.id = id;
		this.employeeid = employeeid;
		this.name = name;
		this.level = level;
		this.getdate = getdate;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getEmployeeid() {
		return this.employeeid;
	}

	public void setEmployeeid(String employeeid) {
		this.employeeid = employeeid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLevel() {
		return this.level;
	}

	public void setLevel(String level) {
		this.level = level;
	}

	public Date getGetdate() {
		return this.getdate;
	}

	public void setGetdate(Date getdate) {
		this.getdate = getdate;
	}

}
