package com.olivee.hrmanager.web.entity;

// Generated 2012-9-28 17:46:35 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * HrEmployee generated by hbm2java
 */
public class HrEmployee implements java.io.Serializable {

	private String id;
	private String orgid;
	private String name;
	private String gender;
	private String hometown;
	private Date birthday;
	private String address;
	private String zipcode;
	private String politicalLandscape;
	private String degree;
	private String educationalLevel;
	private String graduateSchool;
	private Date graduateDate;
	private String specialty;
	private String titles;
	private String telephone1;
	private String telephone2;
	private String telephone3;
	private String email;

	public HrEmployee() {
	}

	public HrEmployee(String id, String name) {
		this.id = id;
		this.name = name;
	}

	public HrEmployee(String id, String orgid, String name, String gender,
			String hometown, Date birthday, String address, String zipcode,
			String politicalLandscape, String degree, String educationalLevel,
			String graduateSchool, Date graduateDate, String specialty,
			String titles, String telephone1, String telephone2,
			String telephone3, String email) {
		this.id = id;
		this.orgid = orgid;
		this.name = name;
		this.gender = gender;
		this.hometown = hometown;
		this.birthday = birthday;
		this.address = address;
		this.zipcode = zipcode;
		this.politicalLandscape = politicalLandscape;
		this.degree = degree;
		this.educationalLevel = educationalLevel;
		this.graduateSchool = graduateSchool;
		this.graduateDate = graduateDate;
		this.specialty = specialty;
		this.titles = titles;
		this.telephone1 = telephone1;
		this.telephone2 = telephone2;
		this.telephone3 = telephone3;
		this.email = email;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getOrgid() {
		return this.orgid;
	}

	public void setOrgid(String orgid) {
		this.orgid = orgid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getHometown() {
		return this.hometown;
	}

	public void setHometown(String hometown) {
		this.hometown = hometown;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	public String getPoliticalLandscape() {
		return this.politicalLandscape;
	}

	public void setPoliticalLandscape(String politicalLandscape) {
		this.politicalLandscape = politicalLandscape;
	}

	public String getDegree() {
		return this.degree;
	}

	public void setDegree(String degree) {
		this.degree = degree;
	}

	public String getEducationalLevel() {
		return this.educationalLevel;
	}

	public void setEducationalLevel(String educationalLevel) {
		this.educationalLevel = educationalLevel;
	}

	public String getGraduateSchool() {
		return this.graduateSchool;
	}

	public void setGraduateSchool(String graduateSchool) {
		this.graduateSchool = graduateSchool;
	}

	public Date getGraduateDate() {
		return this.graduateDate;
	}

	public void setGraduateDate(Date graduateDate) {
		this.graduateDate = graduateDate;
	}

	public String getSpecialty() {
		return this.specialty;
	}

	public void setSpecialty(String specialty) {
		this.specialty = specialty;
	}

	public String getTitles() {
		return this.titles;
	}

	public void setTitles(String titles) {
		this.titles = titles;
	}

	public String getTelephone1() {
		return this.telephone1;
	}

	public void setTelephone1(String telephone1) {
		this.telephone1 = telephone1;
	}

	public String getTelephone2() {
		return this.telephone2;
	}

	public void setTelephone2(String telephone2) {
		this.telephone2 = telephone2;
	}

	public String getTelephone3() {
		return this.telephone3;
	}

	public void setTelephone3(String telephone3) {
		this.telephone3 = telephone3;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
