package com.olivee.hrmanager.web.entity;

// Generated 2012-9-28 17:46:35 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * HrVocationalCertificate generated by hbm2java
 */
public class HrVocationalCertificate implements java.io.Serializable {

	private String id;
	private String employeeid;
	private String name;
	private String getfrom;
	private Date getdate;

	public HrVocationalCertificate() {
	}

	public HrVocationalCertificate(String id, String employeeid) {
		this.id = id;
		this.employeeid = employeeid;
	}

	public HrVocationalCertificate(String id, String employeeid, String name,
			String getfrom, Date getdate) {
		this.id = id;
		this.employeeid = employeeid;
		this.name = name;
		this.getfrom = getfrom;
		this.getdate = getdate;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getEmployeeid() {
		return this.employeeid;
	}

	public void setEmployeeid(String employeeid) {
		this.employeeid = employeeid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getGetfrom() {
		return this.getfrom;
	}

	public void setGetfrom(String getfrom) {
		this.getfrom = getfrom;
	}

	public Date getGetdate() {
		return this.getdate;
	}

	public void setGetdate(Date getdate) {
		this.getdate = getdate;
	}

}
