package com.olivee.hrmanager.web.entity;

// Generated 2012-9-28 17:46:35 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * HrWorkExperience generated by hbm2java
 */
public class HrWorkExperience implements java.io.Serializable {

	private String id;
	private String employeeid;
	private String companyName;
	private String companyNature;
	private String jobNature;
	private String duty;
	private Date beginDate;
	private Date endDate;

	public HrWorkExperience() {
	}

	public HrWorkExperience(String id, String employeeid) {
		this.id = id;
		this.employeeid = employeeid;
	}

	public HrWorkExperience(String id, String employeeid, String companyName,
			String companyNature, String jobNature, String duty,
			Date beginDate, Date endDate) {
		this.id = id;
		this.employeeid = employeeid;
		this.companyName = companyName;
		this.companyNature = companyNature;
		this.jobNature = jobNature;
		this.duty = duty;
		this.beginDate = beginDate;
		this.endDate = endDate;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getEmployeeid() {
		return this.employeeid;
	}

	public void setEmployeeid(String employeeid) {
		this.employeeid = employeeid;
	}

	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public String getCompanyNature() {
		return this.companyNature;
	}

	public void setCompanyNature(String companyNature) {
		this.companyNature = companyNature;
	}

	public String getJobNature() {
		return this.jobNature;
	}

	public void setJobNature(String jobNature) {
		this.jobNature = jobNature;
	}

	public String getDuty() {
		return this.duty;
	}

	public void setDuty(String duty) {
		this.duty = duty;
	}

	public Date getBeginDate() {
		return this.beginDate;
	}

	public void setBeginDate(Date beginDate) {
		this.beginDate = beginDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

}
