package com.olivee.hrmanager.web.entity;

// Generated 2012-9-28 17:46:35 by Hibernate Tools 3.4.0.CR1

/**
 * SysCode generated by hbm2java
 */
public class SysCode implements java.io.Serializable {

	private String id;
	private String keyCode;
	private String code;
	private String name;

	public SysCode() {
	}

	public SysCode(String id, String keyCode) {
		this.id = id;
		this.keyCode = keyCode;
	}

	public SysCode(String id, String keyCode, String code, String name) {
		this.id = id;
		this.keyCode = keyCode;
		this.code = code;
		this.name = name;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getKeyCode() {
		return this.keyCode;
	}

	public void setKeyCode(String keyCode) {
		this.keyCode = keyCode;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
